name: pre-commit
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
permissions:
  contents: write  # Ensure write access for auto-commits
  pull-requests: write
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the token with write access
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pre-commit
        run: python -m pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Commit auto-fixed files
        if: failure()
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Apply pre-commit auto-fixes" || true
          git push
